version = "9.4.2"

[general]
    optimization = 0

    [general.memory]
        size = OPTION_MEMORY_SIZE
        latencies = [["1"], ["1"]]

[simulator]
    optimization = 0



[[sdk]]
    model = "codasip_urisc_v.ia"
    newlib-micro = true
    default-linker-args = "--defsym=_TEXT_START_ADDR=0x1000"
    compiler-rt = true
    startup = true
    newlib = true