pattern = [XLEN, EXTENSION_M, DELIMITER, ENABLE_CACHES, OCD]

[DELIMITER]
    values = ["-"]
    type = delimiter
    default = "-"

# ISA configuration
[XLEN]
    type = uint
    format = "%d"
    default = 32

    [XLEN.values]
        32 = "32I"
        64 = "64I"

[EXTENSION_M]
    type = bool
    default = false

    [EXTENSION_M.values]
        false = ""
        true = "M"

# RISC-V Debugger
[OCD]
    type = bool
    default = false

    [OCD.values]
        false = ""
        true = "d"

[BOOT_START]
    type = uint
    format = "0x%x"
    default = 0x1000

[PROGBUF_START]
    type = expression
    default = "BOOT_START - PROGBUF_SIZE*4"

[PROGBUF_SIZE]
    type = uint
    format = "%d"
    default = 4
    dependency = "OCD"

[ENABLE_SYSBUS_ACCESS]
    type = bool
    default = false
    dependency = "OCD"

[ENABLE_WATCHPOINTS]
    type = bool
    default = true
    dependency = "OCD"

# Memory
[MEMORY_SIZE]
    type = uint
    format = "0x%08x"
    default = 0x80000000

[ENABLE_CACHES]
    type = bool
    default = false

    [ENABLE_CACHES.values]
        false = ""
        true = "ID"

[CACHE_REGS_BASE]
    type = uint
    format = "0x%08xu"
    default = 0x800
    dependency = "ENABLE_CACHES"

